### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by Virv12**
removed unused dependencies
nix v0.24 -> v0.28
env_logger v0.7 -> v0.11
fix clippy warnings

Can we get a release after this gets merged?

### CODE REVIEW

**Review by alerighi — APPROVED** [review]

**Comment by alerighi** [comment]
I will do a release about it. 

By the way, as you can imagine, I no longer actively maintain this project (I've found out that I did no longer have a Rust compiler on my PC!), so if you or anyone else wants to take on this project, I will happily give them access.

**Comment by Virv12** [comment]
You can transfer the ownership of the repo to https://github.com/olimpiadi-informatica/.
I'm not sure what's the best solution for the cargo package, for the time being I can take the role (https://crates.io/users/Virv12).

**Comment by alerighi** [comment]
I prefer to keep the repository on my profile, to be seen as part of my project portfolio. Tough you can of course fork it in your organization, and from now on work on there!

For the cargo package, I've sent you an invite on crates.io.

**Comment by Virv12** [comment]
Thank you!

**Pull request merged**
